sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t gmlgjs11/react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true gmlgjs11/react-app npm run test -- -- coverage
after_success:
  - echo "Test Success"